version: '3.1'
services:
    node-farm:
      image: omaraalsaied/nodefarm:1.1
      ports:
        - 5000:3000
    mongodb:
        image: mongo:4.0
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin 
            MONGO_INITDB_ROOT_PASSWORD: 123456 
    mongo-express:
        image: mongo-express:0.54.0
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: 123456 
            ME_CONFIG_MONGODB_SERVER: mongodb


